# Generated by Django 4.1.2 on 2022-11-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nacimiento',
        ),
    ]
